runtime: custom
env: flex
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 8
# readiness_check:
  # path: "/readiness_check"
  # check_interval_sec: 5
  # timeout_sec: 4
  # failure_threshold: 2
  # success_threshold: 2
  # app_start_timeout_sec: 1800